### PR TITLE
Update agents.mdx with TFC Agent Binary Options

### PR DESCRIPTION
**Pull request by zisom-hc**
### What
Added a table of all options (flags,parameters,etc.) that are available to used by the TFC agent.

### Why
Currently you can only obtain this information by outputting the help message from the TFC agent binary, or docker container. There is currently no documentation for them to go to obtain information about what environment variables they need and can configure. This makes it difficult for practitioner's to discover what's possible, and for support engineering to provide guidance by referring/pointing them to the documentation.

Maybe the information is not best put within a table, or folks may not like the formatting of the table (i used a table generator to be transparent), which is okay. At the very least, i want to get this out to get the ball rolling for implementing this information into our documentation.

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added for moved, renamed, or deleted pages. This requires a separate PR in the [`terraform-website` repository](https://github.com/hashicorp/terraform-website) `redirects.next.js` file.
- [ ] API documentation and the API Changelog have been updated. 
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

### CODE REVIEW

**Comment by ryanuber** [comment]
Just a quick note - 

>  if a user wants to utilize the docker container, there is no documentation for them to go to obtain information about what environment variables they need and can configure.

Keep in mind you can always get the help output from the container as well:

```
docker run hashicorp/tfc-agent:latest -h
```

**Comment by zisom-hc** [comment]
> Just a quick note -
> 
> > if a user wants to utilize the docker container, there is no documentation for them to go to obtain information about what environment variables they need and can configure.
> 
> Keep in mind you can always get the help output from the container as well:
> 
> ```
> docker run hashicorp/tfc-agent:latest -h
> ```

Thank you for the insight; i hadn't realized that.

**Comment by ryanuber** [comment]
This is great, @zisom-hc ! I'm happy to have this type of documentation on the website, and I'll bet users frequently try to find it there.

Regarding the formatting, I think a bulleted list style similar to Nomad's docs may be better suited to this use. It allows the text to flow more naturally and provides more space for longer-form descriptions of the options.

I was also thinking that this documentation might also be prone to staleness. You've inspired me to get this documented though so I took a quick stab at massaging the help output into a markdown format in [this PR](https://github.com/hashicorp/tfc-agent/pull/322). Let me know what you think!

**Comment by zisom-hc** [comment]
Your iteration is much cleaner, and it's awesome that there's some automation to combat staleness as well. Closing out my PR now to be replaced by yours

**Pull request closed without merging**
